spring.application.name=municipalidad-backend-app

#Puerto que se usará para ejecutar la aplicación
server.port=8080

#MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/muni_san_miguel_v2?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

#JPA (validación de entidades, mostrar SQL en consola y formatear el SQL)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Logging SQL (Consulta y parámetros)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7000/realms/municipalidad-gestion-eventos

# Keycloak Admin API
keycloak.admin.server-url=${KEYCLOAK_ADMIN_SERVER_URL:}
keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM:}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:}
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:}
