services:
  backend:
    build: ../backend
    container_name: backend-municipalidad
    env_file:
      - ./.env
    ports:
      - "10.10.2.10:8080:8080"
    volumes:
      - ../credentials/storage-eventos-key.json:/app/credentials/storage-eventos-key.json:ro
    depends_on:
      - keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3 #imagen de keycloak
    container_name: keycloak
    command: start-dev
    env_file:
      - ./.env
    ports:
      - "10.10.2.10:7000:8080"
    volumes:
      - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf #Origen (PC) - DESTINO (Contenedor)
      - ../keycloak-theme/dist_keycloak:/opt/keycloak/providers #Themes generados por Keycloakify
