# ==== Configuración compartida y estable ====

# Motor de base de datos a usar
db=postgres
http-enabled=true
proxy-headers=xforwarded
hostname=https://auth.municipalidadsm.online
health-enabled=true
metrics-enabled=true